services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      STORAGE: ${STORAGE:-postgres}
      ADDR: ${ADDR:-:8080}
      DSN: postgres://${PGUSER:-feed}:${PGPASSWORD:-feed}@postgres:5432/${PGDATABASE:-feed}?sslmode=${PGSSLMODE:-disable}
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    image: migrate/migrate:v4.18.1
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://${PGUSER:-feed}:${PGPASSWORD:-feed}@postgres:5432/${PGDATABASE:-feed}?sslmode=${PGSSLMODE:-disable}"
      - "up"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${PGUSER:-feed}
      POSTGRES_PASSWORD: ${PGPASSWORD:-feed}
      POSTGRES_DB: ${PGDATABASE:-feed}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER:-feed}"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
