package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/google/uuid"

	domainComment "github.com/zmskv/feed-service/internal/domain/comment"
	domainPost "github.com/zmskv/feed-service/internal/domain/post"
	"github.com/zmskv/feed-service/internal/presentation/graphql/generated"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *generated.Comment, first int, after *string) (*generated.CommentConnection, error) {
	id, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, err
	}
	postID, err := uuid.Parse(obj.PostID)
	if err != nil {
		return nil, err
	}
	cursor, err := decodeCursor(after)
	if err != nil {
		return nil, err
	}

	parent := &domainComment.Comment{ID: id, PostID: postID}
	items, hasNext, err := r.comments.ListReplies(ctx, parent, first, cursor)
	if err != nil {
		return nil, err
	}
	return buildCommentConnection(items, hasNext), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *generated.Post, first int, after *string) (*generated.CommentConnection, error) {
	postID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, err
	}
	cursor, err := decodeCursor(after)
	if err != nil {
		return nil, err
	}

	items, hasNext, err := r.comments.ListByPost(ctx, postID, first, cursor)
	if err != nil {
		return nil, err
	}
	return buildCommentConnection(items, hasNext), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first int, after *string) (*generated.PostConnection, error) {
	cursor, err := decodeCursor(after)
	if err != nil {
		return nil, err
	}

	items, hasNext, err := r.posts.List(ctx, first, cursor)
	if err != nil {
		return nil, err
	}
	return buildPostConnection(items, hasNext), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*generated.Post, error) {
	postID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	p, err := r.posts.Get(ctx, postID)
	if errors.Is(err, domainPost.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return postToModel(p), nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	commentResolver struct{ *Resolver }
	postResolver    struct{ *Resolver }
	queryResolver   struct{ *Resolver }
)
