// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_test.go -package=comment_test
//

// Package comment_test is a generated GoMock package.
package comment_test

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	comment "github.com/zmskv/feed-service/internal/application/comment"
	comment0 "github.com/zmskv/feed-service/internal/domain/comment"
	post "github.com/zmskv/feed-service/internal/domain/post"
	pagination "github.com/zmskv/feed-service/internal/pagination"
	gomock "go.uber.org/mock/gomock"
)

// MockPostRepository is a mock of PostRepository interface.
type MockPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepositoryMockRecorder
	isgomock struct{}
}

// MockPostRepositoryMockRecorder is the mock recorder for MockPostRepository.
type MockPostRepositoryMockRecorder struct {
	mock *MockPostRepository
}

// NewMockPostRepository creates a new mock instance.
func NewMockPostRepository(ctrl *gomock.Controller) *MockPostRepository {
	mock := &MockPostRepository{ctrl: ctrl}
	mock.recorder = &MockPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepository) EXPECT() *MockPostRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockPostRepository) FindByID(ctx context.Context, id uuid.UUID) (*post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPostRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPostRepository)(nil).FindByID), ctx, id)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (*comment0.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*comment0.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// ListByParent mocks base method.
func (m *MockRepository) ListByParent(ctx context.Context, postID uuid.UUID, parentID *uuid.UUID, first int, after *pagination.Cursor) ([]*comment0.Comment, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByParent", ctx, postID, parentID, first, after)
	ret0, _ := ret[0].([]*comment0.Comment)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByParent indicates an expected call of ListByParent.
func (mr *MockRepositoryMockRecorder) ListByParent(ctx, postID, parentID, first, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByParent", reflect.TypeOf((*MockRepository)(nil).ListByParent), ctx, postID, parentID, first, after)
}

// ListRepliesByParents mocks base method.
func (m *MockRepository) ListRepliesByParents(ctx context.Context, parentIDs []uuid.UUID, first int, after *pagination.Cursor) (map[uuid.UUID]*comment.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepliesByParents", ctx, parentIDs, first, after)
	ret0, _ := ret[0].(map[uuid.UUID]*comment.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepliesByParents indicates an expected call of ListRepliesByParents.
func (mr *MockRepositoryMockRecorder) ListRepliesByParents(ctx, parentIDs, first, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepliesByParents", reflect.TypeOf((*MockRepository)(nil).ListRepliesByParents), ctx, parentIDs, first, after)
}

// ListTopLevelByPosts mocks base method.
func (m *MockRepository) ListTopLevelByPosts(ctx context.Context, postIDs []uuid.UUID, first int, after *pagination.Cursor) (map[uuid.UUID]*comment.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopLevelByPosts", ctx, postIDs, first, after)
	ret0, _ := ret[0].(map[uuid.UUID]*comment.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopLevelByPosts indicates an expected call of ListTopLevelByPosts.
func (mr *MockRepositoryMockRecorder) ListTopLevelByPosts(ctx, postIDs, first, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopLevelByPosts", reflect.TypeOf((*MockRepository)(nil).ListTopLevelByPosts), ctx, postIDs, first, after)
}

// Save mocks base method.
func (m *MockRepository) Save(ctx context.Context, c *comment0.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), ctx, c)
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPublisher) Publish(c *comment0.Comment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", c)
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisher)(nil).Publish), c)
}
